### ISSUE TITLE
Validator fails to recognize parameters separated by dot in paths

### ISSUE THREAD

**Issue by dang-gyg** [Apicurio/apicurio-data-models#157]
When there is a path with dot between parameters like this:
```/img/{entity_type}/{file_name}/{format}.{ext}```

Then the validator fails with 2 issues:

> /paths[/img/{entity_type}/{file_name}/{format}.{ext}] | Path template "/img/{entity_type}/{file_name}/{format}.{ext}" is not valid.
> /paths[/img/{entity_type}/{file_name}/{format}.{ext}]/get/parameters[3] | Path Parameter "ext" not found in path template.

**Comment by EricWittmann** [comment]
Fixed by https://github.com/Apicurio/apicurio-data-models/pull/158
