### ISSUE TITLE
Investigate support for OpenAPI 3.1.0

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-data-models#168]
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md

**Comment by EricWittmann** [comment]
https://www.openapis.org/blog/2020/10/23/implementers-draft-oas3.1-rc1-available-for-feedback-please-respond-by-nov-8

**Comment by EricWittmann** [comment]
https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc1

**Comment by kilahm** [comment]
Looks like this is almost a year old. I'd like to encourage teams at my company to adopt OAS 3.1 as they start publishing their documents into Apicurio Registry. Seems like this issue needs to be resolved before registry supports OAS 3.1, right?

Is it possible to get a timeline estimate for OAS 3.1 support?

Thanks for all your hard work on Apicurio!

**Comment by EricWittmann** [comment]
There is progress on this, but not enough where I can give a timeline estimate.  You are right that this needs to be accomplished before OAS 3.1 support is available in Registry.

Ping to @Apicurio/developers on this, fwiw.

**Comment by EricWittmann** [comment]
So I know it's been a long road, but Apicurio Data Models version 2.0 (release candidate 1) was just released and it features support for all released versions of OpenAPI **and** AsyncAPI:

https://github.com/Apicurio/apicurio-data-models#project-status

The new version takes a code generation approach to creating the core models for all the versions of the specifications we support.  It's a breaking change, as many APIs and also the surface area of the models has changed.  The core ideas are largely preserved.

There's still work to be done, in particular in the validation and operational transformation areas.  But with the release of 2.0.0.RC1 I think we can close this issue and start to open more granular issues for missing or broken functionality.

Note that I have a PR open to upgrade Registry to data models 2.0 here:

https://github.com/Apicurio/apicurio-registry/pull/3100
