### ISSUE TITLE
Can not find transpiled Typescript files 

### ISSUE THREAD

**Issue by turutosiya** [Apicurio/apicurio-data-models#231]
After I run the following command, I can not find transpiled Typescript files under `target` directory.
```
$ mvn clean package
```
Where are they created?

**Comment by EricWittmann** [comment]
There is a maven profile you need to activate for the transpilation to be done:

`mvn clean package -Ptranspilation`

I've updated the README to reflect this.

Once that is done, you will find all of the typescript files in `target/ts`.

**Comment by EricWittmann** [comment]
https://github.com/Apicurio/apicurio-data-models/commit/4ba17dae8b308a9c5af9d4fd36693e48a64ec458
