### ISSUE TITLE
additionalProperties: true

### ISSUE THREAD

**Issue by thushalya** [Apicurio/apicurio-data-models#589]
Since additionalProperties variable is using AsyncApiSchema type , cannot give the value as true when it comes to create schema for 

 `map<json> `

Here json will be dynamic.  Isn't it good to have it as the type of Object in java.. Or is there any way to set this please point out to me . Thank you

**Comment by EricWittmann** [comment]
Hi @thushalya - unlike OpenAPI, the AsyncAPI specification actually does not allow `boolean` values for `additionalProperties` of an asyncapi schema.  From the [AsyncAPI spec](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#schema-object):

![image](https://user-images.githubusercontent.com/1890703/227562108-50a2a35b-bfd7-40e2-a9b2-dcb9f0e92f95.png)

If you follow the link they include in that section to the `additionalProperties` section of the [JSON Schema Validation spec](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-6.5.6), you will find this:

![image](https://user-images.githubusercontent.com/1890703/227562621-84c1861e-8509-4136-93e8-1aceaac0e166.png)

My reading of this is that the current modeling in Apicurio Data Models v2 is correct.

**Comment by thushalya** [comment]
can you refer to this one https://github.com/asyncapi/jasyncapi/pull/131 
They have already changed it in latest asyncapi model version of jasyncapi

**Comment by EricWittmann** [comment]
Ah ha - that's a subtlety of the JSON schema spec I didn't realize, namely that `true` and `false` are actually VALID JSON SCHEMAS!

My mind is blown.

It's easy enough to fix, fortunately.  Do you want to give it a shot or wait for me?  :)  All you would need to do is change the descriptions in the spec yaml files.  For example, this must be changed:

https://github.com/Apicurio/apicurio-data-models/blob/main/src/main/resources/specs/asyncapi/asyncapi-2.0.yaml#L554-L555

And should become this:

https://github.com/Apicurio/apicurio-data-models/blob/main/src/main/resources/specs/openapi/openapi-3.0.yaml#L507-L508

Then rebuild and see if anything breaks.

**Note**: you would need to make the above change in all of the AsyncAPI yaml files.

**Comment by thushalya** [comment]
Yeah definitely I will do it.
