### ISSUE TITLE
specification not printing in alphabetical order

### ISSUE THREAD

**Issue by thushalya** [Apicurio/apicurio-data-models#590]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/89528929/226636256-6941a601-4d49-4204-b003-649494488913.png">

This is the output that is produced when a yaml file is created using Jackson ObjectMapper's mapper.writer.

As you can see, the messages key is below and the schemas key is above. Nevertheless, if I put this in the asyncapi parser, there won't be any errors. Yet, isn't it lovely to have it generally in a standard asyncapi specification? (messages key to be above  and schemas key to be below).

If someone can look at this, it would be wonderful, this is not just related to messages and schemas.. there also had some ordering problems in different keys as well. The reason I'm assuming this is where the variables declare order .. (attached an image). As you can see schemas variable has been declared above the messages variable.  or it would be the case in modelwriter(attached an image). but I'm not certain.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/89528929/226639241-1deee91a-164f-4540-b4e6-c56ebdb2c067.png">
**variable declare order**

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/89528929/226642521-aad3de40-aeaa-45a6-a642-c924e18d05fd.png">
**model writer**

thank you

**Comment by EricWittmann** [comment]
> In the most recent version of this library, the ordering of properties in the output should be based on the order they are defined in the specification.  If that is not happening then it's a bug.  This applies for standard ordering of properties listed in the specification, not collections of entities. For collections, the ordering should be preserved based on the input file.

**Comment by thushalya** [comment]
> In the most recent version of this library, the ordering of properties in the output should be based on the order they are defined in the specification. If that is not happening then it's a bug. This applies for standard ordering of properties listed in the specification, not collections of entities. For collections, the ordering should be preserved based on the input file.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/89528929/227841551-71e28570-50b8-40e5-8e3d-dcaec66a787a.png">

Hello @EricWittmann ,
As you can see even if I try to set message prior to schema using a setter, it doesn't print in the order what I am setting it. Is this wrong?

**Comment by thushalya** [comment]
@EricWittmann  Yeah yeah I got it
