### ISSUE TITLE
Serialization gives additional fields 

### ISSUE THREAD

**Issue by thushalya** [Apicurio/apicurio-data-models#596]
1) I have used Jackson ObjectMapper to convert AsyncAPI schema object into a Json node  and set it as a extension (because extension needs a jsonNode)... When I did that it has been serilalized into a json node as below image . But as you can see it just  wrapped using additional keyword called "external" instead of letting its children to be as normal extensions 
ex ;- `x-nullable:true `, `x-required: false`

I tried to do this using Gson also and I got the same result. Therefore I am assuming the problem is going inside the Apicurio model

**output**
<img width="250" alt="image" src="https://user-images.githubusercontent.com/89528929/236972295-3e38e9c6-9d08-4fbb-b98e-b68cf30e1dfb.png">

Also this is happening on the AsyncApiSchema class extensions field..this is not a problem in AsyncApiMessage class extensions field. It is doing well in there as I mentioned

-----------------------------------------------------------------------------------

2) Btw I am getting  
 `schema: true` , `entity: true` as in the output of the objectmapper serialization. The reasons, according to my search result, are that the both isEntity method and the isSchema method return true. , therefore Jackson objectmapper will not ignore these default true values even if I use 
` objectMapper.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);`

For a solution, I just extend the AsyncAPISchema25 class and set isEntity and isSchema method as JsonIgnore using (@JsonIgnore annotation) 
but for my POV isn't it good if you can do this inside the model instead of letting the user doing this?.

**source code**
<img width="600" alt="image" src="https://user-images.githubusercontent.com/89528929/236968298-97f61fd5-ea1c-4f7f-81b1-9cba6d6f2813.png">

**output**
<img width="254" alt="image" src="https://user-images.githubusercontent.com/89528929/236968319-b6902813-4b7d-48e8-9a2d-33193b313a63.png">

--------------------------------------------------------------------------------------
3)   I have found another problem  similar to 1st problem when I try to use setAdditionalProperties  method

**source code**
```
check2.setAdditionalProperties(new BooleanUnionValueImpl(new Boolean(true)));
ObjectNode objectNode1=objectMapper.valueToTree(check2);
check1.addExtension("rg",objectNode1);
```
**output**
<img width="250" alt="image" src="https://user-images.githubusercontent.com/89528929/236970064-e4925e0d-274f-4589-9085-c7660a02180b.png">

As you can see output has additional fields instead of showing `additionalProperties: true` . However this is not a problem  when I didn't use serialization. 

Finally I would like to know any alternative way or a particular way to serialize Apicurio model AsyncAPI objects you are using in this model?

**source code if you want to check**
```
package org.example;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.util.DefaultPrettyPrinter;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import io.apicurio.datamodels.Library;
import io.apicurio.datamodels.models.asyncapi.v25.AsyncApi25ComponentsImpl;
import io.apicurio.datamodels.models.asyncapi.v25.AsyncApi25DocumentImpl;
import io.apicurio.datamodels.models.asyncapi.v25.AsyncApi25InfoImpl;
import io.apicurio.datamodels.models.asyncapi.v25.AsyncApi25SchemaImpl;
import io.apicurio.datamodels.models.union.BooleanUnionValueImpl;

public class Main {
    public static void main(String[] args) {
        AsyncApi25DocumentImpl try1 = new AsyncApi25DocumentImpl();
        try1.setAsyncapi("2.5.0");
        AsyncApi25InfoImpl info = new AsyncApi25InfoImpl();
        info.setDescription("ffefed");
        try1.setInfo(info);

        ObjectMapper objectMapper = new ObjectMapper();

        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);
        AsyncApi25SchemaImpl check1 = new AsyncApi25SchemaImpl();
        AsyncApi25SchemaImpl check2 = new AsyncApi25SchemaImpl();
        AsyncApi25ComponentsImpl components = (AsyncApi25ComponentsImpl) try1.createComponents();
        check2.setAdditionalProperties(new BooleanUnionValueImpl(Boolean.TRUE));
        ObjectNode objectNode1 = objectMapper.valueToTree(check2);
        check1.addExtension("rg", objectNode1);

        components.addSchema("hello", check1);
        try1.setComponents(components);

        ObjectNode checking = Library.writeDocument(try1);
        YAMLFactory factory = new YAMLFactory();
        String finalYaml;
        try {
            finalYaml = new ObjectMapper(factory).writer(new DefaultPrettyPrinter()).writeValueAsString(checking);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }

        System.out.println(finalYaml);

    }
}
```

@EricWittmann  hello brother I am asking a quick response from you .please reply if you have time

**Comment by thushalya** [comment]
@EricWittmann  Kind reminder for this brother

**Comment by EricWittmann** [comment]
Hey, very sorry I missed this.

How are you converting the async API object into JSON?

Are you using the library class? Or are you using a Jackson objectMapper?

**Comment by EricWittmann** [comment]
Ouch sorry for the delay on this.  I had a rough run of bad luck earlier in the year and I just flat out missed this.  :(

I'm looking at this now, and it seems yes you have hit a few bugs here.  I'll put together some tests and fix this up asap.

**Comment by EricWittmann** [comment]
OK looking more closely at this it's confusing.  I'm not quite sure what you're trying to accomplish with this code, so maybe you can clarify that.  What is the output JSON/YAML structure you are hoping for?

Some information that might help:

* You should never use `ObjectMapper` to serialize an apicurio data model - you should use something from `Library` instead
* Adding an extension to a data model does require a `JsonNode` instance.  I would recommend `JsonNodeFactory` for that in most cases (for creating simple `TextNode` instances)

Serializing the apicurio data model object and then taking the resulting JsonNode and assigning it back to the apicurio data model as an extension is a weird thing to do.  Not sure why you are doing that.

**Comment by EricWittmann** [comment]
Here is modified source code that **maybe** does what you're trying to do:

```json
public class Main {
    public static void main(String[] args) {
        AsyncApi25DocumentImpl try1 = new AsyncApi25DocumentImpl();
        try1.setAsyncapi("2.5.0");
        AsyncApi25InfoImpl info = new AsyncApi25InfoImpl();
        info.setDescription("ffefed");
        try1.setInfo(info);

        AsyncApi25ComponentsImpl components = (AsyncApi25ComponentsImpl) try1.createComponents();

        AsyncApi25SchemaImpl check1 = (AsyncApi25SchemaImpl) components.createSchema();
        AsyncApi25SchemaImpl check2 = (AsyncApi25SchemaImpl) components.createSchema();
        check2.setAdditionalProperties(new BooleanUnionValueImpl(Boolean.TRUE));
        ObjectNode objectNode1 = Library.writeNode(check2);
        check1.addExtension("rg", objectNode1);

        components.addSchema("hello", check1);
        try1.setComponents(components);

        String finalYaml = Library.writeDocumentToJSONString(try1);

        System.out.println(finalYaml);

    }
}
```
